spring:

  profiles:
    active: local
  # mysql 사용 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # 하이버네이트가 실행한 모든 sql문을 콘솔로 출력
        show_sql: true
        # sql문을 가독성 있게 출력
        format_sql: true

logging:
  level:
    org.hibernate: info

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/Ae_stagram?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: 1234

firebase:
  sdk:
    path: firebase-accesskey.json

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${MYSQL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

firebase:
  sdk:
    path: ${FIREBASE_SDK_PATH}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${MYSQL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

firebase:
  sdk:
    path: ${FIREBASE_SDK_PATH}
