spring:
  profiles:
    include: aws, db

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
        # 하이버네이트가 실행한 모든 sql문을 콘솔로 출력
        show_sql: true
        # sql문을 가독성 있게 출력
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

logging:
  level:
    org.hibernate: info

firebase:
  sdk:
    path: ${FIREBASE_SDK_PATH}

app:
  page-size: 10