spring:

  datasource:
    url: jdbc:mysql://localhost:3306/Ae_stagram?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: 1234

  # mysql 사용 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # 하이버네이트가 실행한 모든 sql문을 콘솔로 출력
        show_sql: true
        # sql문을 가독성 있게 출력
        format_sql: true

logging:
  level:
    org.hibernate: info

firebase:
  sdk:
    path: src/main/resources/firebase-accesskey.json